apiVersion: v1
kind: Service
metadata:
  name: jasminegraph-master-service
  labels:
    service: jasminegraph-master
spec:
  ports:
    - port: 7777
      name: 'server-port'
      nodePort: 30001
    - port: 7778
      name: 'server-data-port'
      nodePort: 30002
  selector:
    type: master
    service: jasminegraph
  type: NodePort
