apiVersion: v1
kind: PersistentVolume
metadata:
  name: "jasminegraph-worker<worker-id>-data"
  labels:
    application: jasminegraph
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "var/tmp/worker<worker-id>"