apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "jasminegraph-worker<worker-id>-data-claim"
  labels:
    application: jasminegraph
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi