name: Style Check

on:
    push:
      branches: [master]
    pull_request:
      branches: [master]

jobs:
    style-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - run: sudo apt-get install cpplint
            - name: cpplint check
              if: ${{!contains(github.event.pull_request.labels.*.name, 'Skip cpplint Check')}}
              run: cpplint --linelength=120 --filter=-build,-runtime,-readability/todo,-whitespace/todo,-readability/casting,-readability/braces,-readability/fn_size,-legal/copyright --exclude=./src/util/sqlite3/ --recursive .